### PR TITLE
Adding First Case to run_all

### PR DESCRIPTION
**Pull request by geiercc**
@kathrynline @agale123 @edwardlou12 @nriggio I've merged my First Case.R with main and now am just adding this into the run_all.R file

### CODE REVIEW

**Comment by agale123** [comment]
I'm not seeing the change to the run_all.R script in this PR?

**Comment by geiercc** [comment]
@agale123 Oops, thanks Alison! I realized I didn't pull correctly, it should be updated now.

**Comment by agale123** [comment]
For the jhu_deaths_01.26.2021_with_country_code.csv file, I think I added those originally and then moved them to the intermediate folder so all of those are the raw_data files with country code added. Is that sufficient for your script?

**Review by kathrynline — CHANGES_REQUESTED** [review]
If you can delete that .csv, and then make sure you can run run_all.r, this looks good to me.

**Pull request merged**
